[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/admin.28013c0e86d123a1c9bb.css"
  to = "/admin.css"
  status = 301

[[redirects]]
  from = "/admin.10d9575087eebc049c09.css"
  to = "/admin.css"
  status = 301

[[redirects]]
  from = "/admin.*"
  to = "/admin.js"
  status = 301

[[redirects]]
  from = "/admin-*.js"
  to = "/admin.js"
  status = 302

[[redirects]]
  from = "/admin-*.css"
  to = "/admin.css"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
